version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    ports:
      - 3000:3000

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: unless-stopped
    container_name: app_backend
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    command: npm start

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app
    volumes:
     - ./nginx:/etc/nginx/conf.d
    stdin_open: true
    ports:
      - 9000:9000